### ISSUE TITLE
Null Pointer Help!

### ISSUE THREAD

**Issue by DARKTEMPLE9** [flankerhqd/JAADAS#8]
I build the latest version jar from source code. I try to run this awesome project. However, I failed. 
I try to fix this null pointer bug but I failed. Anyone idea to solve this problem? 

Transforming android.support.v4.view.accessibility.AccessibilityEventCompatIcs... 
java.io.FileNotFoundException: /Users/test/android_tool/JAADAS/config/ConstantRules.groovy (/Users/test/android_tool/JAADAS/config/ConstantRules.groovy)
	at groovy.lang.GroovyCodeSource.<init>(GroovyCodeSource.java:106)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:186)
	at org.k33nteam.jade.propagation.track.APIVulnManager.initFromGroovy(APIVulnManager.java:40)
	at org.k33nteam.jade.propagation.track.APIVulnManager.<init>(APIVulnManager.java:31)
	at org.k33nteam.jade.propagation.base.NaiveAPIChecker.<init>(NaiveAPIChecker.scala:19)
	at org.k33nteam.jade.drivers.CheckDriver.doNaiveAPIScan(CheckDriver.scala:132)
	at org.k33nteam.jade.drivers.CheckDriver.fastentry(CheckDriver.scala:99)
	at main$.main(main.scala:75)
	at main.main(main.scala)
Exception in thread "main" java.lang.NullPointerException
	at org.k33nteam.jade.propagation.track.APIVulnManager.initFromGroovy(APIVulnManager.java:49)
	at org.k33nteam.jade.propagation.track.APIVulnManager.<init>(APIVulnManager.java:31)
	at org.k33nteam.jade.propagation.base.NaiveAPIChecker.<init>(NaiveAPIChecker.scala:19)
	at org.k33nteam.jade.drivers.CheckDriver.doNaiveAPIScan(CheckDriver.scala:132)
	at org.k33nteam.jade.drivers.CheckDriver.fastentry(CheckDriver.scala:99)
	at main$.main(main.scala:75)
	at main.main(main.scala)

**Comment by flankerhqd** [comment]
Hello:

Do you put the ConstantRules.groovy in the location as specified ? The NPE is caused by JAADAS cannot find the groovy source file for rules at ` /Users/test/android_tool/JAADAS/config/ConstantRules.groovy`. You may need to modify part of the command line to `-c /Users/test/android_tool/JAADAS/jade/config`

The rule files are at `https://github.com/flankerhqd/JAADAS/tree/master/jade/config` of this repo.

**Comment by DARKTEMPLE9** [comment]
Thanks for your help! I solved it.
