### ISSUE TITLE
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00

### ISSUE THREAD

**Issue by Jessie9122** [flankerhqd/JAADAS#9]
Hi, Flanker
I encountered an issue like this:
`$ java -jar D:\barca\JAADAS\jaadas-0.1\jade-0.1.jar vulnanalysis -f D:\barca\app\system_app_DownloadProviderUi_DownloadProviderUi.apk      -p F:\tools\adtnew\sdk\platforms -c D:\barca\JAADAS\jaadas-0.1\config\ --fastanalysis
********************************************
enabled plugins: implements custom verifier that always return true
Webview js file access misconfigurations
Webview ssl handler impl onReceivedSslError, lead to SSL vulnerability
X509TrustManager empty impl, lead to SSL vulnerability
FAKEID reloaded vulnerability
Check webview save password disabled or not
Scan for ZipEntry vulnerable to unzip directory traversal vulnerability
********************************************
********************************************
enabled modules: constapicheck, crash analysis
********************************************
Using 'F:\tools\adtnew\sdk\platforms\android-23\android.jar' as android.jar
Warning: exception while processing dex file 'D:\barca\app\system_app_DownloadProviderUi_DownloadProviderUi.apk'
Exception: org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Warning: java.lang.ref.Finalizer is a phantom class!
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:151)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:70)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:88)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:56)
        at soot.DexClassProvider.classesOfDex(DexClassProvider.java:121)
        at soot.SourceLocator.getClassesUnder(SourceLocator.java:206)
        at soot.Scene.loadNecessaryClasses(Scene.java:1361)
        at org.k33nteam.jade.drivers.CheckDriver.prepareMethodTraversal(CheckDriver.scala:77)
        at org.k33nteam.jade.drivers.CheckDriver.fastentry(CheckDriver.scala:98)
        at main$.main(main.scala:75)
        at main.main(main.scala)`

why  it shows that no dex file, but it has a classes.dex file in it

**Comment by flankerhqd** [comment]
Hi:

If you are scanning a system app file, the code file in it maybe odexed, currently the Soot DexBackend doesn not support odex, this might be the reason. You can send the sample to me if you like, and I can help debug this issue.

**Comment by Jessie9122** [comment]
Thank you for answer me
I opened the apk and found a classes.dex in it , later I will send a sample to u

**Comment by Jessie9122** [comment]
here is the apk
[apk.docx](https://github.com/flankerhqd/JAADAS/files/1090049/apk.docx)

**Comment by Jessie9122** [comment]
When you open the zip, if you cannot unzip it directly, please try these steps:
1.	Double click zip in the document
2.	Double click to the parent directory     
3.	Then the apk(Calculator.zip) is in the parent directory, copy it ,done

**Comment by flankerhqd** [comment]
Hello:

I think it's related to an upstream dexlib issue, see https://github.com/JesusFreke/smali/issues/493 when parsing Android 7.1 application. I will try to see if we can merge the upstream changes.

**Comment by Jessie9122** [comment]
Thank you very much!
We could not use the tool also in Android6.0 application, but I am not sure if it is the same reason

**Comment by flankerhqd** [comment]
Did you get same error output? I thought this should only appear on Android O since they use a new odex format.

**Comment by Jessie9122** [comment]
The error I feed back is in Android N app, not in Android O
